### ISSUE TITLE
Other builds of 3D Pinball Space Cadet

### ISSUE THREAD

**Issue by Sunlitspace542** [k4zmu2a/SpaceCadetPinball#10]
There are a few other versions of 3D Pinball, will support for these be added?
https://tcrf.net/Proto:3D_Pinball:_Space_Cadet

**Comment by k4zmu2a** [comment]
No, there are no plans to support data from pre-release builds.

The BL is from Windows XP release version of 3DPB, with some hacks to support Full Tilt data.
Theoretically, any data should work, if it has all the groups and entries that BL is hard-coded to look for.

The files that I test with:
PINBALL.DAT SHA-1 C1A616EDB0985CF8AADFB2A1029DADAE16CDFCC5
CADET.DAT SHA-1 DD81B3488D6DAA14584788BD2A045E08C820597B

**Comment by Sunlitspace542** [comment]
I've tested the 3 preview builds and they all seem to be playable, the Plus version requires some modifications to the game data folder structure, but it also works.
