### ISSUE TITLE
SpeceCadetPinball binary for openSUSE

### ISSUE THREAD

**Issue by Afsalmc** [k4zmu2a/SpaceCadetPinball#101]
hey not an issue . I just want to mention that instalable builds of this game is available for openSUSE through obs . https://software.opensuse.org/package/SpaceCadetPinball .

The last time i checked it works fine in Tumbleweed ! And thanks for the efforts **k4zmu21**

**Comment by k4zmu2a** [comment]
That is nice to hear, I welcome ease of use and higher availability.
If I were to package the game with no restrictions, I would have included FT data in addition to 3DPB.

**Comment by k4zmu2a** [comment]
openSUSE users rejoice)
