### ISSUE TITLE
Adding .deb as release format?

### ISSUE THREAD

**Issue by LucyLikesYourFace** [k4zmu2a/SpaceCadetPinball#107]
Would adding a download for a .deb be in the scope of this repo?
I know that ideally this should be added to appropriate package managers, however i am still figuring my way round all that.
If anyone has any recommendations regarding this please let me know.

**Comment by k4zmu2a** [comment]
Sorry, distribution specific packaging and builds are out of scope here.
Maybe Debian non-free will accept your package, I don’t know specifics on how to apply for that.

**Comment by LucyLikesYourFace** [comment]
Thank you, thought as much but wanted to ask anyway.
I'm looking into official methods, or maybe distributing some other way
I have what i've got so far on my fork if anyone is interested

**Comment by LucyLikesYourFace** [comment]
Getting package into debian might be a no-go, even in nonfree:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1001894
@k4zmu2a thoughts on this?

**Comment by k4zmu2a** [comment]
Well, Debian rep is correct in a sense.
Original source code is licensed under unknown license from Cinematronics (Maxis->EA) to MS.
I license my code (which is derived indirectly from the original code) under MIT.
Some might argue that original license prevents existence of all forms of compatible code.

There is not much you can do to change Debian position; it is easier to just forget about them.

**Comment by kowalski7cc** [comment]
@LucyLikesYourFace At best you probably can maintain a PPA or something like that

**Comment by kowalski7cc** [comment]
Also, a deb/rpm file could be put in the Platform/Linux folder and allow package maintainers to build from upstream to some third party repositories (I'm thinking something like RPM Fusion for Fedora)

**Comment by coreybruce** [comment]
> Would adding a download for a .deb be in the scope of this repo? I know that ideally this should be added to appropriate package managers, however i am still figuring my way round all that. If anyone has any recommendations regarding this please let me know.

Hey @LucyLikesYourFace have you tried the flatpak of this? 

https://flathub.org/apps/details/com.github.k4zmu2a.spacecadetpinball

**Comment by k4zmu2a** [comment]
I am not adding distro-specific packaging.
