### ISSUE TITLE
Got it working, but no sound and SDL error.

### ISSUE THREAD

**Issue by Alex313031** [k4zmu2a/SpaceCadetPinball#108]
Compiled for linux, copied PINBALL.dat from an XP machine into ../bin, and install libsdl2-dev and libsdl2-mixer-dev and libudev-dev. 
unning the game has no sound and shows this error

SDL Error: Failed loading udev_device_get_action: /lib/x86_64-linux-gnu/libSDL2-2.0.so.0: undefined symbol: _udev_device_get_action

Running on Debian Bullseye.

**Comment by k4zmu2a** [comment]
Sounds and music are not part of .dat file, they are stored in .wav and .mid files.
With only .dat file you get the smallest game rip experience)
Ideally, you should copy the whole game data set. 

I don’t know about that udev stuff, probably something to do with SDL.
It worked for me with no errors in Sid.

**Comment by Alex313031** [comment]
Can I use the whole data set from my XP VM?

**Comment by Alex313031** [comment]
@k4zmu2a COOL. Got it working. Copied all .wav  and .mid files and FONTS.dat (does that do anything?) and it runs like on XP?
Also, why don't you make linux releases? Is it because it wouldn't necessarily be portable from one distro to another? If you would like, I would be willing to build for debian 10/11 & ubuntu 18.04/20.04 and package them as a zip with the .dat and music files (if thats allowed)

Also, maybe this is unorthodox to do since its self-promotion, but I'd like more users so.... lol, but I make a Chromium fork for linux/windows called Thorium, with patches and enhancements, and multiple compiler optimizations that make it around 5-10% faster than vanilla chromium often shipped with distros. > https://github.com/Alex313031/Thorium Check it out if you want.

**Comment by k4zmu2a** [comment]
Good, I am glad that you got it working.
FONTS.dat is unused, even by original game.
Try playing with Full Tilt data, it has higher resolution sprites.

>why don't you make Linux releases…

Yes, mostly because dynamic builds are distro dependent.
Truly universal build would be fully static. Or maybe AppImage or something like that.

I am not going to distribute third party builds or original game assets.
Maybe more distros will package the game in the future.

Sorry, I am not part of your target audience.
I run Windows as host OS on all my boxes.

**Comment by Alex313031** [comment]
@k4zmu2a Made this with the assets. And I am including the original XP assets because XP. Nuff said lol.
https://github.com/Alex313031/Linux-Pinball

**Comment by k4zmu2a** [comment]
Fine by me.
However, I cannot recommend unknown third-party builds to anyone, so no links, sorry.
If compiling is impossible, I’d rather have people use the recently published Flatpak.
