### ISSUE TITLE
Flatpak build

### ISSUE THREAD

**Issue by catsout** [k4zmu2a/SpaceCadetPinball#109]
Please, consider supporting [Flatpak](http://docs.flatpak.org/en/latest/introduction.html#reasons-to-use-flatpak) and publishing  SpaceCadetPinball on [Flathub](https://github.com/flathub/flathub/wiki/App-Submission).

**Comment by k4zmu2a** [comment]
I might give it a try in the future, but I have some concerns:
My package without game data would be inferior to some other distributions. I would rather have an unencumbered third party make the package with data.
I am hesitant to take on any unnecessary responsibilities, such as applying and maintaining it.

**Comment by catsout** [comment]
>My package without game data would be inferior to some other distributions.

Flatpak can avoid this thought extra data which will be download and install through script when user install, like the aur in archlinux.

**Comment by kowalski7cc** [comment]
https://github.com/kowalski7cc/com.github.k4zmu2a.spacecadetpinball maybe?

**Comment by kowalski7cc** [comment]
I'm trying on branch https://github.com/kowalski7cc/com.github.k4zmu2a.spacecadetpinball/tree/fluidsynth to make MIDI work, but inside the sandbox `fluidsynth -i $SDL_SOUNDFONTS /app/bin/PINBALL.MID` plays music fine, but the game will not.
Any thoughts?

**Comment by k4zmu2a** [comment]
I am fine with any package, as long as I don’t have to worry about it)

I have no clue how this flatpack sandbox works, I thought it could use system MIDI synth and font.
The best bet is to look for clues in a working package with SDL MIDI playback.

**Comment by catsout** [comment]
@k4zmu2a Do you consider maintaining SpaceCadetPinball on flathub?   

@kowalski7cc You may need to rebuild SDL2_mixer to support fluidsynth

**Comment by catsout** [comment]
Here is example that uses timidity + freepats
https://github.com/flathub/com.corsixth.corsixth/blob/master/com.corsixth.corsixth.yml#L71

**Comment by kowalski7cc** [comment]
@catsout Nice catch! I added it, but still no music. I find the following libs:
/app/lib/libSDL2_mixer-2.0.so.0      /app/lib/libSDL2_mixer.a   /app/lib/libSDL2_mixer.so
/app/lib/libSDL2_mixer-2.0.so.0.2.2  /app/lib/libSDL2_mixer.la

**Comment by catsout** [comment]
@kowalski7cc You need build fluidsynth before sdl2_mixer, and it's default static link.

**Comment by kowalski7cc** [comment]
@catsout thanks! Fixed and merged on main.

**Comment by kowalski7cc** [comment]
Now the last missing doubt I have is why on chromeos it doesn't show the window with wayland 😂
But probably it's some chromeos quirk...

**Comment by catsout** [comment]
https://github.com/flathub/org.openttd.OpenTTD/blob/master/org.openttd.OpenTTD.yaml#L66  
This soundfont is only 38M, seems sf3 is better than sf2 at compression

**Comment by catsout** [comment]
Maybe https://github.com/musescore/MuseScore/raw/2.1/share/sound/FluidR3Mono_GM.sf3 (19M) is better  
https://packages.debian.org/sid/fluidr3mono-gm-soundfont

**Comment by k4zmu2a** [comment]
> Do you consider maintaining SpaceCadetPinball on flathub?
No, I have no plans to maintain anything other than the project itself.
I’d rather spend my limited time working on the game.

About original game data: it is my choice not to distribute it, my flatpack would be without it.
I don’t know if that will even work with sandbox and stuff.
This is why I believe that third parties can produce better packages.

**Comment by catsout** [comment]
>About original game data: it is my choice not to distribute it, my flatpack would be without it.  

The flatpak can do this through download the data at installing, rather than distributing it   
If you choose not to do this, you can let user manually download it.  
But this requires dynamic game data path, like `DATA=/path/to/data SpaceCadetPinball`.  

>I don’t know if that will even work with sandbox and stuff.

It will work as long as it works on other linux distributions.  
Also there are many sdl2 based applications in flathub.

**Comment by kowalski7cc** [comment]
https://flathub.org/apps/details/com.github.k4zmu2a.spacecadetpinball
We can close this issue 🙂
