### ISSUE TITLE
scaling options?

### ISSUE THREAD

**Issue by neofeo** [k4zmu2a/SpaceCadetPinball#11]
Hi buddy! nice work here!!!
can I ask you if there is any way to implement scaling to 1080p (having proper aspect ratio?
you know, changing resolutions it's a bit annoying.

also, I noted you added other resolutions for the table but they are greyed, why is that?

BR, Salvador. Nice to see @GeorgeMcMullen  involved here!! hahah

**Comment by k4zmu2a** [comment]
Hello, fellow pinball enjoyer)

Arbitrary window scaling is already implemented, in both WindowsClassic (the one in 1.1.1 release) and SDL versions.
To use it, just resize the window. Uniform scaling is an option, under Options->Window.

Note that full screen option in WindowsClassic version does not use scaling.
It uses exclusive full screen in native table resolution (the one from resolution options).
I don’t plan adding fixed scaling factors, like 1080p.

Those resolution options you see are for Full Tilt cadet table data.
Data from Windows version only has sprites in lowest resolution, that’s why other resolutions are grayed out.

**Comment by neofeo** [comment]
Ohh great! I got it!! Thanks !!!

**Comment by neofeo** [comment]
I've just made a video about it, I had an small calling issue, but probably related to mesa or cinnamon I guess. 
awesome!!!

https://www.youtube.com/watch?v=VlQkn4o9fNQ

**Comment by k4zmu2a** [comment]
It is nice that it compiles on ARM.

On flickering in void: I didn’t find an obvious flaw in my code that can cause this.
Added explicit clear color, maybe it will help.

Resolution menu is back in v2, Full Tilt data is needed to use it.
