### ISSUE TITLE
[Feature Request] Could a setting for sounds/music volume be added?

### ISSUE THREAD

**Issue by mity** [k4zmu2a/SpaceCadetPinball#120]
The original sound effects are imho too loud in comparison to almost any other applications or media used/played on the same computer. So it would be great if we can configure the volume, without turning the sound effects off completely.

**Comment by k4zmu2a** [comment]
Ok, I will look into it. It is probably easy to add with SDL.
My original intent was to leave this task to system volume mixer.

**Comment by k4zmu2a** [comment]
Volume options are ready.

**Comment by k4zmu2a** [comment]
Released in V2.1.0
