### ISSUE TITLE
Created a icon you guys can use

### ISSUE THREAD

**Issue by coreybruce** [k4zmu2a/SpaceCadetPinball#126]
Hey guys I  just wanted to contribute to this awesome project by recreating a modern version of the original icon. I recently compiled and packed this for myself Manjaro Arm64 and created a new icon so here it is.

This is the original icon:
![image](https://user-images.githubusercontent.com/8393780/150664775-9eb2d868-f604-455e-a7af-e83e5236c250.png)

And here is my Re created icon I made in Krita:
![pinball](https://user-images.githubusercontent.com/8393780/150664783-44d9f747-a27f-4329-a531-9a556bb9e125.png)

Your free to use it and if you want the .kra file I can give that to you. :)

**Comment by k4zmu2a** [comment]
Thank you, but we already have HQ icon upscale that is closer to the original look.
See https://github.com/k4zmu2a/SpaceCadetPinball/blob/master/SpaceCadetPinball/Icon_192x192.png.

**Comment by coreybruce** [comment]
> Thank you, but we already have HQ icon upscale that is closer to the original look. See https://github.com/k4zmu2a/SpaceCadetPinball/blob/master/SpaceCadetPinball/Icon_192x192.png.

Ahh ok that's all good, wasn't sure if you had one so I thought I would make one. :smile: 

Do you need help with upscaling and fixing up the pinball sprites etc?

**Comment by k4zmu2a** [comment]
Not in immediate future.
I am yet to add support for alternative table resolutions.
It is not a high priority task, and it might not happen at all.

**Comment by coreybruce** [comment]
> Not in immediate future. I am yet to add support for alternative table resolutions. It is not a high priority task, and it might not happen at all.

Oh okay fair enough 😃
