### ISSUE TITLE
Assist and provide you with Linux x64 and Arm64 binaries

### ISSUE THREAD

**Issue by coreybruce** [k4zmu2a/SpaceCadetPinball#127]
Hey Again, would you like some help getting binaries compiled for Linux x64 and Arm64? I can easily Help and compile for both as I have a Linux PC and my Raspberry pi 4 which I have already packaged a  local package on my Manjaro Arm64 via my pi 4 8gb.

**Comment by k4zmu2a** [comment]
Hello.
I have no need for Linux binaries.
My strategy is to use only universal distribution methods, such as building from source.
I considered making a static build for x64 and x86, decided against it in the end.

The are several 3rd party packages for various distros that provide dynamic builds.
There is also a Flatpack package, which is kind of universal.

**Comment by coreybruce** [comment]
> Hello. I have no need for Linux binaries. My strategy is to use only universal distribution methods, such as building from source. I considered making a static build for x64 and x86, decided against it in the end.
> 
> The are several 3rd party packages for various distros that provide dynamic builds. There is also a Flatpack package, which is kind of universal.

Ahh ok, does that flatpak have arm64 support?

**Comment by k4zmu2a** [comment]
Flatpak package itself probably supports building for arm.
But I am not sure if Flathub provides arm binaries.

**Comment by coreybruce** [comment]
> Flatpak package itself probably supports building for arm. But I am not sure if Flathub provides arm binaries.

I'm pretty sure it already does :)

**Comment by kowalski7cc** [comment]
Yes, it supports both x86_64 and aarch64 :)
