### ISSUE TITLE
TABA2.MDS and TABA3.MDS aren't heard during gameplay when using Full Tilt files

### ISSUE THREAD

**Issue by LegoLoco7** [k4zmu2a/SpaceCadetPinball#129]
I love this decompilation and all the features it has, but I did notice a slight issue when playing using the files from Full Tilt! Pinball's Space Cadet, and that is TABA2.MDS and TABA3.MDS aren't played at all during gameplay. [This video](https://www.youtube.com/watch?v=7Zi7kCqtN1M) should give you a basic idea of when those themes are supposed to play if you remake the code for it rather than using the code from the actual game. (In said video, TABA2.MDS appears at [0:17](https://youtu.be/7Zi7kCqtN1M?t=17), while TABA3.MDS appears at [17:38](https://youtu.be/7Zi7kCqtN1M?t=1058).)

The 3D Pinball for Windows - Space Cadet demo doesn't have either of these themes, so the new code could be bypassed if using the demo files or using the Prefer 3DPB Data option with any music-related demo files present.

Though I now realize for TABA3.MDS, you'd have to answer [this](https://github.com/k4zmu2a/SpaceCadetPinball/issues/57) issue as well. Just thought I'd mention after looking.

I also just realized now that this is already a planned feature. That's good to know, at least. I apologize if I've wasted your time.

**Comment by k4zmu2a** [comment]
This is a known problem, playback of second and third tracks is not yet implemented.
It is a side effect of project structure: 3DPB code with FT support added on top.

I am not going to add FT things just based on observed behavior, I prefer basing them on decompilation.
Rest assured, I aim to add all FT game play features, eventually.

**Comment by LegoLoco7** [comment]
I was guessing so.

I'm not exactly sure why you wouldn't do that considering it's just simple music cues, but okay, I guess. I wish you luck.

**Comment by k4zmu2a** [comment]
Support for all FT midi tracks is now ready in v2 and v1.
TABA3 is currently unreachable because it needs multi ball support.
