### ISSUE TITLE
MacBook Air M1

### ISSUE THREAD

**Issue by WaterFloat** [k4zmu2a/SpaceCadetPinball#130]
[https://url52.ctfile.com/d/2996552-47439381-33ba69](https://url52.ctfile.com/d/2996552-47439381-33ba69)
（PWD：8722）
![未命名](https://user-images.githubusercontent.com/23094284/157822631-bc6d6268-3645-43ea-8054-bbe6d3184497.jpg)

**Comment by parkerlreed** [comment]
Is there a bug? Is this a confirmation that it works?

**Comment by k4zmu2a** [comment]
This is most likely a success story/binary share.
However, the project is already known to compile on ARM arch and under macOS.

In fact, the game should compile on most little-endian architectures.
It might even work on exotics, as it was tested to compile and run on Elbrus VLIW.

**Comment by WaterFloat** [comment]
> 有错误吗？这是否证实了它的工作原理？

I only know a little bit of compilation knowledge, and I compiled it by accident. I don't know if there is a bug, but it does work fine.

**Comment by k4zmu2a** [comment]
Compiling things can be rewarding, especially when it works)
