### ISSUE TITLE
Idioma en español

### ISSUE THREAD

**Issue by EliasDIPA** [k4zmu2a/SpaceCadetPinball#139]
Hola, recuerdo que el juego original fue traducido al español, ¿sería posible agregar la traducción al español?

**Comment by k4zmu2a** [comment]
> Hello, I remember that the original game was translated into Spanish, would it be possible to add the Spanish translation?
Hi.
V1 already includes all translations that original 3DBP had, including Spanish.
V2 in English only at the moment. Localization support is a planned V2 feature.

**Comment by EliasDIPA** [comment]
¿Y cuáles son las diferencias entre V1 y V2?

**Comment by k4zmu2a** [comment]
>And what are the differences between V1 and V2?

They both have mostly the same gameplay features; the difference is in the tech used.
V1 is based on the original code, with some gameplay and UI features added. It is for Windows only, just like the original.
V2 is a cross-platform port of V1. It has different UI that adds more options but lacks localization support.

**Comment by EliasDIPA** [comment]
ok gracias, podrias agregar un boton para cambiar el idioma
en opciones?

**Comment by k4zmu2a** [comment]
Release V2.1.0 contains partial localization support.
