### ISSUE TITLE
Not compiling when SDL version has patch level 1 but is >2.0.2

### ISSUE THREAD

**Issue by hauke96** [k4zmu2a/SpaceCadetPinball#145]
Hi,

the check for the SDL version is not working when a newer version has patch level 1. For example SDL 2.6.1 has the patch level is 1 but is generally newer than 2.0.2. The following line then uses the wrong variable:

https://github.com/k4zmu2a/SpaceCadetPinball/blob/6f00b57eb9e541cd837acfba5b637fbc21ee6cdb/SpaceCadetPinball/pch.h#L40

A check like this should work better:
```c++
#if SDL_MIXER_MAJOR_VERSION * 100 + SDL_MIXER_MINOR_VERSION * 10 + SDL_MIXER_PATCHLEVEL >= 202
```

**Comment by k4zmu2a** [comment]
Hello.
Thank you for reporting this, I totally missed that sudden SDL_mixer version bump.
Now it should fixed.

**Comment by hauke96** [comment]
Thanks, it now works :)
