### ISSUE TITLE
MacBook Pro 2019 - Could not load game data

### ISSUE THREAD

**Issue by builtbydc** [k4zmu2a/SpaceCadetPinball#146]
After compiling using `cmake` and attempting to run, I get the following error:

**Could not load game data**

The .dat file is missing.
Make sure that the game data is present in any of the following locations:
working directory
/Users/danielcarlson/SpaceCadetPinball/bin/
/Users/danielcarlson/Library/Application Support/SpaceCadetPinball/
/usr/local/share/SpaceCadetPinball/
/usr/share/SpaceCadetPinball/

**Comment by tomrow** [comment]
It can't find the game resources, make sure you have them and they're located properly and try again. You can get these files from a copy of Full Tilt! Pinball, or a Windows operating system from the late 90s to the early 2000s.

**Comment by k4zmu2a** [comment]
This project does not include game data, only game code.
Users are supposed to provide their own copy of supported game data.

**Comment by yodalee** [comment]
Is this legal to provide this here?
You can get the game data from AUR package [here](https://aur.archlinux.org/packages/spacecadetpinball-git)

**Comment by win98se** [comment]
> Is this legal to provide this here? You can get the game data from AUR package [here](https://aur.archlinux.org/packages/spacecadetpinball-git)

IMHO, that AUR package providing proprietary blobs may cause trouble to this mainstream project, and even to the author. Read #1 and #41.

**Comment by k4zmu2a** [comment]
My position on the data:
The project itself does not distribute original game data.
Naturally, this self-imposed restriction does not apply to 3rd party forks, packages, links, etc.
I believe it would be unreasonable and unrealistic to demand 3rd parties to comply with arbitrary distribution rules.

**Comment by k4zmu2a** [comment]
As designed.
