### ISSUE TITLE
fultilt version behaving like the windows version

### ISSUE THREAD

**Issue by AkyraF** [k4zmu2a/SpaceCadetPinball#155]
hi i have a full tilt dat but its behaving like the windows version is there something that can be done about it?

**Comment by k4zmu2a** [comment]
Hello.

That is normal for the current state of the game.
You see, this project is based on 3DPB code, with FT support spliced in.
FT data and game logic support is not 100% done, it is a work in progress.

Which of the missing FT features were the most noticeable for you?

**Comment by AMNatty** [comment]
In the FullTilt version, it seems the bumper upgrade lights can only be toggled on, not off.

**Comment by AMNatty** [comment]
The hyperspace kickout sound is interesting, seems like there are multiple FullTilt versions and the one I used in Wine doesn't. Since that version doesn't even work in an XP VM, I'll try running it on 95 to see whether it's actually a Wine thing or not.

**Comment by k4zmu2a** [comment]
FT control has a lot of subtle changes in most of its subs.
I will be going through all of them sometimes in the future.
Right now, I am focusing on component changes.

In my copy of FT (32 bit, v1.1), hyperspace kickout/blackhole sound does not cut off.
The same is true in my project, both in 3DPB and FT, so all is well here?

Technical reason for the cutoff - 3DPB and early version of FT use WaveMix for sounds.
There is a limit on number of simultaneously playing sounds – hardcoded at 8.
With flag spinner stealing multiple slots, it is easy to imagine how a few rapid ball collisions can stop the hyperspace sound.
Both of my game versions have this sound limit, I believe it is safe to assume that retail version of FT (that uses Direct Sound) also has some limit.

**Comment by AMNatty** [comment]
I see, thank you for the explanation.

**Comment by k4zmu2a** [comment]
Release V2.1.0 contains improved FT compatibility.
Please create a new issue if V2.1.0 is missing any FT behaviors.
