### ISSUE TITLE
On Linux change of control keys are not working 

### ISSUE THREAD

**Issue by xcom169** [k4zmu2a/SpaceCadetPinball#16]
On Linux change of control keys are not working. No configuration window is available.

**Comment by k4zmu2a** [comment]
Player controls dialog was not implemented.
V2 is in pre-release, control dialog was scheduled to be implemented last.
It just so happens that I worked on it this week, and now it is ready.
Similar issue: #17.

**Comment by xcom169** [comment]
Thank you very much.

**Comment by parkerlreed** [comment]
This appears to be implemented now! Working great.
