### ISSUE TITLE
Also possible for the two other 

### ISSUE THREAD

**Issue by Thomas20232030** [k4zmu2a/SpaceCadetPinball#160]
Thanks very much for the version of space cadet which runs fine for me on windows 10. Do you think it would be possible to make...

DragonsKeep
Skulduggery

available? 

Thanks, Thomas

**Comment by k4zmu2a** [comment]
You are very welcome, Thomas.

To answer your question: yes, adding the rest of FT tables is technically possible.
I might do it, after all currently planned features.
The amount of work it takes can be compared to doing the whole process all over again, once per table.
Knowledge of the codebase and components shared between tables helps of course.

See more details in my reply to a similar question in #148.

**Comment by Thomas20232030** [comment]
Hello Andrey, 

that´s fine and I understand the priority. I thought, that it would be easier but I am really dumb in this case;=) 

Thank you very much for your great effort to transfer Space Cadet to such a great exoerience!!!!

Thomas

 

Von: Muzychenko Andrey ***@***.***> 
Gesendet: Donnerstag, 3. November 2022 06:20
An: k4zmu2a/SpaceCadetPinball ***@***.***>
Cc: Thomas Hoppe ***@***.***>; Author ***@***.***>
Betreff: Re: [k4zmu2a/SpaceCadetPinball] Also possible for the two other (Issue #160)

 

You are very welcome, Thomas.

To answer your question: yes, adding the rest of FT tables is technically possible.
I might do it, after all currently planned features.
The amount of work it takes can be compared to doing the whole process all over again, once per table.
Knowledge of the codebase and components shared between tables helps of course.

See more details in my reply to a similar question in #148 <https://github.com/k4zmu2a/SpaceCadetPinball/issues/148> .
