### ISSUE TITLE
Frustration-free mode

### ISSUE THREAD

**Issue by haarp** [k4zmu2a/SpaceCadetPinball#161]
Hi and thanks for this neat project! I never expected to be able to run this classic natively.

One annoying thing about this Pinball is the possibility to lose due to no fault of your own. Either because the ball falls directly through the gap in the middle, out of reach of the flippers. Or because you hit one of the out-lanes multiple times, pulling up the ramp over the kicker.

This can be frustrating, especially when you let young kids play. They're not very good to begin with, and losing to such bs mechanics steals their fun.

Would you consider implementing a frustration-free mode? Maybe reset the out-lane ramps after a while, and lengthening the flippers just a little?

Thanks!

**Comment by k4zmu2a** [comment]
Hello)

Such mode could be done.
Except for the flipper geometry part, that is not easy to do.
How about this: new cheat “easy mode” that makes center post and the kickers stay always on?

**Comment by haarp** [comment]
That sounds like a plan!

**Comment by k4zmu2a** [comment]
Frustration-free mode is ready.

**Comment by haarp** [comment]
Indeed it is. Seems to be working well so far. Thanks a bunch! :)
