### ISSUE TITLE
Focus/remember player name in high scores

### ISSUE THREAD

**Issue by haarp** [k4zmu2a/SpaceCadetPinball#165]
When you reach a new high score, the high score board should automatically give keyboard focus to the player name, and/or remember the previously entered name instead of "Player x". Thanks!

**Comment by k4zmu2a** [comment]
Added auto keyboard focus for player name text box in high score dialog, score submit by enter.


In my opinion, caching player names makes little sense, especially in hotseat mode.
With all edge cases, such feature scores low on my arbitrary complexity/benefit scale)

**Comment by haarp** [comment]
Just verified, it works. Thanks!
