### ISSUE TITLE
Enhancement request - Add Pause to Player Controls

### ISSUE THREAD

**Issue by MattTheQuick** [k4zmu2a/SpaceCadetPinball#168]
I've got this running on my linux-ified Chromebook and as such, I don't have an F3 button to pause. Can you add either an auto-pause feature to the game when anything in the menu is clicked or maybe add the Pause option to the Player Controls so players can map that button to something other than F3.

Love this project! Thanks for all the hard work on this.

**Comment by k4zmu2a** [comment]
Configurable menu shortcuts is great idea. Not so sure about menu auto-pause.
I’ve added all menu shortcuts to the controls menu.

You are very welcome, hard work can be fulfilling if done right)

**Comment by k4zmu2a** [comment]
Rebindable pause key feature was released in V2.1.0
