### ISSUE TITLE
Adding paused text to top screen

### ISSUE THREAD

**Issue by fyredragon69** [k4zmu2a/SpaceCadetPinball#170]
Like the Windows version of the game, when it's paused, the smaller box would display "Game paused F3 to resume". I think it would be a nice QoL addition to the port having that text show up when the game is paused, obviously substituting F3 for START.

**Comment by fyredragon69** [comment]
I've also noticed that when a game is over, it will say F2 starts new game, instead of X.

**Comment by k4zmu2a** [comment]
> Pause text on top screen

Please clarify, what do you mean by “top screen”.
Pause notification is already implemented the same way as in the original game, see attached screenshot.
![image](https://user-images.githubusercontent.com/33288308/218009332-fe764472-e3ba-4ce3-8397-1463a688de30.png)

> X instead of F2 in control prompts

I did not plan to implement this feature - control prompt substitution based on active/last used input device.
I might consider it after everything else is done.

**Comment by fyredragon69** [comment]
When I refer to the top screen, I mean the upper screen on the 3DS. When pausing the game, it does not show the "Game Paused F3 to Resume" text while paused.

**Comment by k4zmu2a** [comment]
I see it now; you are talking about the 3DS source port.
In this project (https://github.com/k4zmu2a/SpaceCadetPinball), I only accept issues about the desktop version of the game.

You should raise your issue in the 3DS source port project:
https://github.com/MaikelChan/SpaceCadetPinball/tree/3ds

**Comment by k4zmu2a** [comment]
3DS issue, off topic.
