### ISSUE TITLE
Add way to disable newly added confirmation on exit

### ISSUE THREAD

**Issue by ffes** [k4zmu2a/SpaceCadetPinball#173]
In 9454e11fd9a06b6cde30249b53859393cb56bed6 you added a confirmation when you exit the game. Could you make an option to disable this question?

**Comment by k4zmu2a** [comment]
Sure, I can do that.
That dialog is mostly meant as a safeguard for exit shortcut.
How about this: instead of adding new option, I could remove confirmation for exit done from the menu?
This way menu will work as before, and exit shortcut will keep its confirmation.

**Comment by ffes** [comment]
Sounds like a good compromise to me

**Comment by k4zmu2a** [comment]
It is ready, exit from menu no longer asks for confirmation.

**Comment by ffes** [comment]
Tried it out and it works as expected

**Comment by k4zmu2a** [comment]
Released in V2.1.0
