### ISSUE TITLE
Cmake error

### ISSUE THREAD

**Issue by pillowyfish98** [k4zmu2a/SpaceCadetPinball#175]
i keep getting this error when trying to compile in Visual studio 
![image](https://user-images.githubusercontent.com/48302889/232156352-b6712d32-fac3-475b-8871-2ac6e72cdb1a.png)

**Comment by k4zmu2a** [comment]
This error is probably caused by missing CMake packages.
By default, devel SDL libs are expected in project root at ./Libs/SDL2 and ./Libs/SDL2_mixer.
You need to either extract them there or set you custom path to the libs in CMakeLists.txt.
