### ISSUE TITLE
Cannot pre-charge spacebar launch before ball is placed

### ISSUE THREAD

**Issue by deadmeu** [k4zmu2a/SpaceCadetPinball#179]
Holding spacebar does nothing if you press it before the ball is placed and the "Awaiting Deployment" message is displayed.

Running the latest Flatpak build under Wayland.

**Comment by k4zmu2a** [comment]
This is a bug, 3DPB mode should allow plunger pullback at any time.

**Comment by k4zmu2a** [comment]
Fixed in 18c80a0.

**Comment by k4zmu2a** [comment]
Released in V2.1.0
