### ISSUE TITLE
Uncapped FPS/UPS?

### ISSUE THREAD

**Issue by Sunlitspace542** [k4zmu2a/SpaceCadetPinball#18]
Can the Framerate and Updates per second be uncapped?

**Comment by parkerlreed** [comment]
You can click on them and set a new value. Is that not working? (I upped FPS but obviously harder to tell when the screen is only 60Hz)

**Comment by parkerlreed** [comment]
Requires a double click to type in a new value and enter to save. Works instantly for me. 
![image](https://user-images.githubusercontent.com/841440/135688847-d4587dea-c44d-405c-a8ee-bafff3282f34.png)

**Comment by Sunlitspace542** [comment]
I mean remove the 360fps/ups limit entirely

**Comment by k4zmu2a** [comment]
This a reasonable feature to request, added.

UPS/FPS ratio still applies when UPS is uncapped.
Original BL does not support sub-millisecond frame times. 
Nothing bad happens, it just skips updates until dt accumulates >1 ms.
I might change that in the future.

Also those UPS controls are drag sliders; you can also set them with the mouse.
