### ISSUE TITLE
SpaceCadePinball.3dsx for android Citrix emulator, does not see a pinball

### ISSUE THREAD

**Issue by ngohogwarts** [k4zmu2a/SpaceCadetPinball#184]
When I launch SpaceCadetPinball.3dsx on Android Citrix emulator, it shows all the graphics, and everything Except a pinball. All the controller are function correctly except I don't see a ball. Can you find me a solution to make this program work.  I understand this is for 3DS to work properly but I really want to work on Android Citrix emulator to work too.  I love the layout of this software. Thank you, J
in Android
/storage/citra-emu/sdmc/3ds/SpaceCadetPinball/
/storage/citra-emu/sdmc/3ds/dspfirm.cdc

**Comment by k4zmu2a** [comment]
Your issue is about 3DS source port; please forward it to the 3DS source port developer: https://github.com/MaikelChan/SpaceCadetPinball/tree/3ds.
I can only help you with issues that affect desktop version of the game.

**Comment by tomrow** [comment]
There's a bug in Citra's dynamic recompiler that causes the game to softlock. It works if you disable the dynamic recompiler.

**Comment by ngohogwarts** [comment]
> 



> There's a bug in Citra's dynamic recompiler that causes the game to softlock. It works if you disable the dynamic recompiler.

Wow, you're amazing. It works. Thank you so much, millions thank you.

**Comment by k4zmu2a** [comment]
The issue with Citra for Android has been resolved.
