### ISSUE TITLE
Missing .dat

### ISSUE THREAD

**Issue by miszterx** [k4zmu2a/SpaceCadetPinball#190]
Hi,

Sorry for the dummy questions, but I am sure I am lost in the instructions.
I can see there are already compiled binaries. Even for Mac. I am interesting now for the Mac version.
The working app is in the downloadable file.
If I try to run it it complains about the following: 

Cloud not load game data
The .dat file is missing.
Make sure that the game data is present in any of the following locations:
working directory
/Applications/Games/SpaceCadetPinball.app/Contents/Resources/
/Users/miszterx/Library/Application Support/SpaceCadetPinball/
/usr/local/share/SpaceCadetPinball/
/usr/share/SpaceCadetPinball/

It is clear. Even on the page, it is mentioned the game data is missing, I need to take care of this part.

And here comes my issue. The page talks about source files as 2 exe files, then how to compile probably even the binary.
But is it even for the data file. I grabbed the two exe files, and put in the mentioned folder, but the error said the .dat file is missing.

So now I am confused Is it a special file what I should find somewhere and put it in the folder? Or even for this data file needs to compile, how the readme mentioned?

Thanks for the help.

**Comment by k4zmu2a** [comment]
Hello.
In order to run the game, you need to place the original game resources into one of the paths listed by the game.
Game resource are not included in this repository, only game code.
Ideally, you should be using resources from your own copy of the original game.

DAT file is main game resource, example DAT placement:
/Applications/Games/SpaceCadetPinball.app/Contents/Resources/PINBALL.DAT
Or
/Applications/Games/SpaceCadetPinball.app/Contents/Resources/CADET.DAT

**Comment by valterschutz** [comment]
I seem to have the same issue. After cloning the repo, compiling and running the executable I get the error
`Game version: 2.1.0
Command line: 
Compiled with: SDL 2.26.3; SDL_mixer 2.6.3; ImGui 1.89.2 WIP HW
Using SDL renderer: opengl
BL error: Could not load game data
The .dat file is missing.
Make sure that the game data is present in any of the following locations:
working directory
/home/valter/Downloads/SpaceCadetPinball/bin/
/home/valter/.local/share/SpaceCadetPinball/
/usr/local/share/SpaceCadetPinball/
/usr/share/SpaceCadetPinball/`
even though I have a .dat file in the bin folder (and also .local/share). I am running Fedora Linux.

**Comment by valterschutz** [comment]
> I seem to have the same issue. After cloning the repo, compiling and running the executable I get the error `Game version: 2.1.0 Command line: Compiled with: SDL 2.26.3; SDL_mixer 2.6.3; ImGui 1.89.2 WIP HW Using SDL renderer: opengl BL error: Could not load game data The .dat file is missing. Make sure that the game data is present in any of the following locations: working directory /home/valter/Downloads/SpaceCadetPinball/bin/ /home/valter/.local/share/SpaceCadetPinball/ /usr/local/share/SpaceCadetPinball/ /usr/share/SpaceCadetPinball/` even though I have a .dat file in the bin folder (and also .local/share). I am running Fedora Linux.

A friend of mine found the solution:
The program only checks for `pinball.dat` and `PINBALL.DAT` but not for `PINBALL.dat` which is what I had named it.

**Comment by miszterx** [comment]
Thanks for all the support! Now it worked fine. I have found a working data file on the archive.org: https://archive.org/details/pinballxp
It is working now on Mac.

**Comment by miszterx** [comment]
solved

**Comment by k4zmu2a** [comment]
Original game files all had uppercase names. 
Mixed case names such as PINBALL.dat can only work on Windows.
