### ISSUE TITLE
sound1.wav has distortion effect

### ISSUE THREAD

**Issue by BPzeBanshee** [k4zmu2a/SpaceCadetPinball#191]
Example here:
https://github.com/k4zmu2a/SpaceCadetPinball/assets/10321244/6fad6102-eadc-4c67-9f6f-5ebb0d31b453

Not much I can really say on this one. Doesn't happen with OG pinball.exe.

**Comment by k4zmu2a** [comment]
It is the same issue as #187.
In short: x64 sdl_mixer introduces artifacts into SOUND1.WAV (the startup sound).
For me, this happens always on Windows and sometimes on Linux. Both in V2.0.1 and V2.1.0.
SOUND1.WAV does not clip when played with media players.

Workaround: try x86 version of the game.

**Comment by k4zmu2a** [comment]
As it turns out, a resampling bug in SDL itself caused this.
With the latest version of SDL SOUND1.WAV plays without distortion.
I have updated Windows binaries for V2.1.0 release.

**Comment by BPzeBanshee** [comment]
My apologies for the duplicate bug report, I did search but missed the other post. 

I can confirm this fixed the issue on my end so I'll hit the 'Close with comment' button. Thank you! :)
