### ISSUE TITLE
fluidsynth warning (non critical)

### ISSUE THREAD

**Issue by Martinligabue** [k4zmu2a/SpaceCadetPinball#195]
I use Arch btw.
I compiled the source from github, and I have freepats-general-midi as the soundfont for playing background music.
I get this warning in the logs, which doesn't affect the game, but I think it can be fixed.

`fluidsynth: warning: Instrument not found on channel 2 [bank=0 prog=11], substituted [bank=0 prog=0]`

Hope this helps

**Comment by k4zmu2a** [comment]
This looks like an error with your sound font and/or Fluidsynth.
The warning implies that your sound font is missing some instrument.

I don’t see this error on my Debian Sid with Fluidsynth + TimGM6mb.
There is nothing to fix on my side - the game just plays original MIDI file without modifications.

**Comment by Martinligabue** [comment]
> This looks like an error with your sound font and/or Fluidsynth. The warning implies that your sound font is missing some instrument.
> 
> I don’t see this error on my Debian Sid with Fluidsynth + TimGM6mb. There is nothing to fix on my side - the game just plays original MIDI file without modifications.

I installed that because it was in the aur script, I'll notify the aur mantainer then
