### ISSUE TITLE
.dat file needed

### ISSUE THREAD

**Issue by demo308** [k4zmu2a/SpaceCadetPinball#196]
I am on mac and it says ".dat file needed"

**Comment by k4zmu2a** [comment]
That is expected, the game needs assets in order to run.
You are supposed to procure them yourself.
See more details in similar story: #190.

**Comment by demo308** [comment]
I will use
https://archive.org/details/pinballxp

**Comment by charlesthobe** [comment]
On UNIX-like systems the program needs the names of all data files to be in uppercase.
Also I think this issue can be safely closed.
