### ISSUE TITLE
Flatpak version 2.1.0 don't start

### ISSUE THREAD

**Issue by celtic34fr** [k4zmu2a/SpaceCadetPinball#198]
Hi, and thanks for your great work.

After updating my flatpak version to 2.1.0 (Linux mint 21.2  cinnamon flavor), as previous version, the program don't start.

When i try to start it in a bash shell, it return :

->start command : 
```/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=SpaceCadetPinball com.github.k4zmu2a.spacecadetpinbal```
or : 
```flatpak run com.github.k4zmu2a.spacecadetpinball```

-> return in all cases : 
```Game version: 2.1.0
Command line: 
Compiled with: SDL 2.28.4; SDL_mixer 2.6.3; ImGui 1.89.2 WIP HW
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: radeonsi
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: radeonsi
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  152 (GLX)
  Minor opcode of failed request:  3 (X_GLXCreateContext)
  Value in failed request:  0x0
  Serial number of failed request:  168
  Current serial number in output stream:  169
```

**Comment by k4zmu2a** [comment]
Hello.

According to the logs, something is wrong with your GPU drivers. 
Things you could try:
•	Build and run the game from source, to check if the issue comes from Flatpak or not.
•	Fix your Radeon GPU driver, radeonsi from log.
•	Setup software rendering with Mesa, swrast from log.

**Comment by celtic34fr** [comment]
With the last update of the flatpak environment, the application will start normally as before.

I close the issue.
