### ISSUE TITLE
[Question] Other 2 "Full Tilt! Pinball" Tables, features

### ISSUE THREAD

**Issue by Sunlitspace542** [k4zmu2a/SpaceCadetPinball#20]
When will tables/features exclusive to Full Tilt be added?

**Comment by k4zmu2a** [comment]
I most likely will not be adding support for DRAGON and PIRATE tables.
Decompiling without symbols is harder; I don’t like them enough to go that far.

CADET features not found in 3DPB – maybe after v2.0 release.
Is there any particular FT CADET feature you are missing and would like to see sooner?

**Comment by Sunlitspace542** [comment]
The one feature I would like to see would be multi-ball mode.
also codebase question; how does the game detect the "hidden test" cheat code?

**Comment by Sunlitspace542** [comment]
I'd like to see Multiball mode added.
