### ISSUE TITLE
Reversed Controls

### ISSUE THREAD

**Issue by rradzevicius1** [k4zmu2a/SpaceCadetPinball#205]
How can I have correct controls on this pinball game?

When i play it on Steam Deck OLED it has reversed flippers. Right flipper corresponds to L2 button and left flipper corresponds to R2 button. i tried to remap buttons but unsuccessfully. How can this be fixed?

**Comment by rradzevicius1** [comment]
![IMG_4011](https://github.com/k4zmu2a/SpaceCadetPinball/assets/163435618/990bbde8-c19e-4868-aae0-34951882c926)

**Comment by tomrow** [comment]
Sounds like the default Desktop mode controls of Steam OS, where the right trigger simulates the left mouse button.

Add it to Steam as a non-Steam game, and go back to the Gaming mode. Use Steam Input to configure the controls. 

Last I checked, the Flatpak (Discover store) version can't read gamepads at all so you will need to configure Steam Input to simulate a mouse and keyboard.

**Comment by parkerlreed** [comment]
Or long hold the Start button to switch into gamepad mode.

**Comment by tomrow** [comment]
It's been a while since I used the Flatpak. I mostly use a build I compiled myself. Didn't know holding START changes the mode, that would explain why my system behaves differently to others.

**Comment by rradzevicius1** [comment]
> Sounds like the default Desktop mode controls of Steam OS, where the right trigger simulates the left mouse button.
> 
> Add it to Steam as a non-Steam game, and go back to the Gaming mode. Use Steam Input to configure the controls.
> 
> Last I checked, the Flatpak (Discover store) version can't read gamepads at all so you will need to configure Steam Input to simulate a mouse and keyboard.

What would be the steps to add non-Steam game to Steam?

**Comment by tomrow** [comment]
Open Steam from the desktop mode and view your Library. Underneath the list is a button with a Plus on it.
Click the button, and then click the non-Steam game option in the menu that appears. 
A dialog should appear with some of your app menu items and a Browse button. Pinball should appear in the list of apps. Check Pinball's check box and then click the confirmation button.

**Comment by rradzevicius1** [comment]
Thank you for your input!
