### ISSUE TITLE
Controller bindings are not responding

### ISSUE THREAD

**Issue by stemy2** [k4zmu2a/SpaceCadetPinball#208]
Hello,

I'd like to use my xbox controller, but despise they are set in the bindings, it doesn't work. If i try to bind any command to a controller's button, it does nothing when i press the said button.

**Comment by Takiro** [comment]
If you're using the Flatpak version, make sure *Device access* is enabled in the Flatpak permissions  
![image](https://github.com/user-attachments/assets/e46782de-a2f2-40fb-b81a-4c0fdb963ad1)
