### ISSUE TITLE
[Suggestion] ARM/ARM64 binaries?

### ISSUE THREAD

**Issue by neozeed** [k4zmu2a/SpaceCadetPinball#21]
I have Visual Studio 2019 so I was able to take the WindowsClassic branch and build binaries, and 'they just work'!  It's great to have  something native for us Windows on ARM (WoR?) Users.  Anyways perhaps you could add binaries?
![pinball arm64](https://user-images.githubusercontent.com/9031439/135794654-88f66817-5b27-446f-bdcb-ad8c0378829c.jpg)

I guess I could upload my builds, but for safety's sake maybe it's best if you upload your own?

Just a suggestion!

[SpaceCadetPinball ARM(32-64).zip](https://github.com/k4zmu2a/SpaceCadetPinball/files/7275460/SpaceCadetPinball.ARM.32-64.zip)

**Comment by k4zmu2a** [comment]
I don’t see why not, if it as easy as adding build platform.

Added build definitions and binaries (untested) under v1.1.1 release.
I will add ARM VS configs in v2 (master) later.

**Comment by neozeed** [comment]
super cool thanks!  I'll let you know on my ASUS how it goes!
