### ISSUE TITLE
Aborted (core dumped) on XFCE Arch Linux

### ISSUE THREAD

**Issue by OzzyHelix** [k4zmu2a/SpaceCadetPinball#213]
Hello I installed it from the AUR using this package and it core dumps on Arch Linux with XFCE. I intend to report the same problem on the AUR package but I thought you guys should know its failing to run on XFCE at least for me. idk it might be something with xfce still using X11 but idk
https://aur.archlinux.org/packages/spacecadetpinball-git

```
Game version: 2.1.1 DEV
Command line: 
Compiled with: SDL 2.30.3; SDL_mixer 2.8.0; ImGui 1.89.2 WIP HW
Using SDL renderer: opengl
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string: construction from null is not valid
Aborted (core dumped)

```

**Comment by k4zmu2a** [comment]
This is a problem with string handling, most likely - some path assumed always not null is null on your machine.
Would be nice to see a stack trace for this crash, can you run the program under gdb?

**Comment by OzzyHelix** [comment]
at the time I was trying to rice my XFCE desktop to look like XP with this project 
https://github.com/rozniak/xfce-winxp-tc/tree/master
and on a fresh install of xfce it launches just fine

**Comment by OzzyHelix** [comment]
on a fresh copy of xfce it runs fine so will be closing this sorry to waste your time
