### ISSUE TITLE
Patches for Full Tilt! Pinball

### ISSUE THREAD

**Issue by Sunlitspace542** [k4zmu2a/SpaceCadetPinball#23]
You may want to look into these 2 update patches for Full Tilt!, as they may include bug fixes and other stuff:
https://archive.org/details/FULLPTCH
https://archive.org/details/TILTFIX

**Comment by k4zmu2a** [comment]
I did consider which version of FT to use for reference.
And I believe that I am using the latest 32 bit version – v1.1 from 17.05.96 (SHA-1 in readme).
It comes pre-patched on CD image.

Just to be sure, I tried the patches:
The first one worked, said that .dat is already patched, .exe is different from source or patched.
I assume that only newer .exe could go on CD with latest .dat.
The second one is for DOS, no point to apply to FULLTILT32.
