### ISSUE TITLE
Support for translated versions

### ISSUE THREAD

**Issue by BulletBlaster** [k4zmu2a/SpaceCadetPinball#28]
Localized editions of Windows XP include translated versions of Space Cadet, I have attached a screenshot of the Polish version:

![SpaceCadetPolish](https://user-images.githubusercontent.com/67292925/136700628-b8649b88-58ca-4d67-8566-1831c880666e.png)

Could support for them be added? What would have to be done?

Also, where are the translated strings and font placed? Inside PINBALL.DAT or PINBALL.EXE? Running the compiled binary inside the Polish version's directory makes the game run in English, so I think it's the former.

**Comment by altiereslima** [comment]
Space Cadet Pinball 3D (Portuguese Brazilian)
[Space Cadet Pinball 3D (Portuguese Brazilian).zip](https://github.com/k4zmu2a/SpaceCadetPinball/files/7585470/Space.Cadet.Pinball.3D.Portuguese.Brazilian.zip)

**Comment by k4zmu2a** [comment]
Portuguese Brazilian is already added, it will probably be released as part of 1.2.
Try it in the attached RC build:
[SpaceCadetPinballx86_v1.2RC.zip](https://github.com/k4zmu2a/SpaceCadetPinball/files/7585956/SpaceCadetPinballx86_v1.2RC.zip)


Actually, I added all of the XP languages, here is the full list:
English 
Russian 
TraditionalChinese 
SimplifiedChinese 
Polish 
German 
Japanese 
French 
Italian 
Hungarian 
Portuguese 
BrazilianPortuguese 
Czech 
Danish 
Finnish 
Hebrew 
Arabic 
Greek 
Spanish 
Korean 
Dutch 
Norwegian 
Swedish 
Turkish

**Comment by k4zmu2a** [comment]
Translation support was released as part of 1.2.
