### ISSUE TITLE
Highscore insertion

### ISSUE THREAD

**Issue by mk-ship-it** [k4zmu2a/SpaceCadetPinball#33]
When creating further highscores, unless you're landing in the "last" spot compared to the existing highscores, there seems to be no dummy entry on the pre-rendered list underneath.

That means that if my high score lands in spot 1, I can only see the previously existing 2nd, 3rd etc. places, with the current first spot seemingly overwritten.

**Comment by k4zmu2a** [comment]
Bugfix released in v2.0.1
