### ISSUE TITLE
Maxis variant not supported even by renaming the DAT file

### ISSUE THREAD

**Issue by Skywalker13** [k4zmu2a/SpaceCadetPinball#34]
Hello

Here the tree for the Maxis variant:
![image](https://user-images.githubusercontent.com/397862/137310085-5966ebbf-e26b-45fb-992a-a456fe2d9d09.png)

It comes from this release:
![image](https://user-images.githubusercontent.com/397862/137310389-47d82d22-e836-48db-97d7-60954c72eff9.png)

For example, if I rename just the DAT file like this:
![image](https://user-images.githubusercontent.com/397862/137310580-083b4761-2b4d-458c-a3d8-f10d51322c55.png)

The result is:
```
$ ./SpaceCadetPinball 
terminate called after throwing an instance of 'std::bad_array_new_length'
  what():  std::bad_array_new_length
Abandon
```

**Comment by Skywalker13** [comment]
Maxis version is more beautiful:
![image](https://user-images.githubusercontent.com/397862/137311054-8b586911-d89d-4829-9a2b-7553add070d0.png)

**Comment by k4zmu2a** [comment]
Hi.

Pinball 95 appears to be an alternative release of Full Tilt pinball.
Full Tilt data is supported in this project.

Judging by the screenshot, the only difference from FT is lowercase file names.
The contents could be different of course.
Rename cadet.dat into CADET.DAT to pass it as FT data to the game.
If that works, finalize transition to FT by renaming the rest of the files and folders uppercase.
I don’t know if it will work or not, as I could not source Pinball 95 download.

**Comment by Skywalker13** [comment]
It works, thank you!
