### ISSUE TITLE
DAT file is missing when running on MacOS M1 chip

### ISSUE THREAD

**Issue by brandenco** [k4zmu2a/SpaceCadetPinball#36]
Error is displayed when running on Mac M1 apple silicone

<img width="362" alt="Screen Shot 2021-10-14 at 9 52 13 PM" src="https://user-images.githubusercontent.com/37084158/137424899-75ef40de-3ea9-4e9c-94e6-2d9aaa4b0b1c.png">

**Comment by brandenc40** [comment]
> This error is shown when the game cannot find main game resource: PINBALL.DAT or CADET.DAT.
> Resources should be in the same folder as game executable.
> Resources are not included in this project, you have to provide them yourself.

> Lack of game resources in this repo is by design. It is to make the project seem more legal than it really is. This concept is widely used in similar game projects.
> 
> Lack of sound is understandable; you need to download the sounds and music if you want them to play. Consider downloading the whole game data set.

Thank you this is helpful, I'd recommend explaining this in the README to avoid this confusion for others in the future.

**Comment by k4zmu2a** [comment]
README already has this info:
>“How to play: Place compiled executable into a folder containing original game resources (not included).”

It must be this succinct to stay easily readable.
