### ISSUE TITLE
Splash screen background not working

### ISSUE THREAD

**Issue by rctgamer3** [k4zmu2a/SpaceCadetPinball#38]
SpaceCadetPinball only shows the tiny bitmap image in the center. pinball.exe goes into a quasi full-screen mode until it is finished loading.

**Comment by k4zmu2a** [comment]
I don’t think there is anything wrong with v1 startup.
Startup is exactly the same as 3DPB, with two differences:
•	There is no black background around splash.
•	There is no delay after splash is shown.

v1 does not support borderless window, only exclusive full-screen.
The game is supposed to go full-screen immediately after splash.

**Comment by k4zmu2a** [comment]
Works as designed.
