### ISSUE TITLE
Idea for Cross-platform

### ISSUE THREAD

**Issue by 0n1cOn3** [k4zmu2a/SpaceCadetPinball#4]
Hi

I am not sure if this could help for port it to other platforms 🤷🏻‍♂️

https://visualgdb.com/tutorials/porting/linux/

**Comment by k4zmu2a** [comment]
Hello.

VisualGDB might make porting easier, but I am not sure if I should use it.
It is a paid tool and it might be simpler to debug Linux stuff locally.
Also, VS has a native alternative to VisualGDB: debugging in WSL2 with X11.

**Comment by k4zmu2a** [comment]
The idea has been considered.
