### ISSUE TITLE
Suggestion: Put the keyboard controls in the README

### ISSUE THREAD

**Issue by sbrl** [k4zmu2a/SpaceCadetPinball#44]
Awesome project! I can't figure out how to play it though, because the keyboard controls aren't documented and the "player controls" option in the menu doesn't work.

**Comment by k4zmu2a** [comment]
I am not sure about putting default controls in readme.

But more importantly, which version of the game are you running?
Both v1 and v2 are supposed to have working player control dialog.

**Comment by sbrl** [comment]
I just clicked the link in the README to play it in the browser. Ubuntu 21.04, latest Firefox Beta.

**Comment by k4zmu2a** [comment]
Then this is a wrong repo for this bug.
That Emscripten source port is based on an older code.
Take it up with alula in https://github.com/alula/SpaceCadetPinball.

**Comment by k4zmu2a** [comment]
Sorry, I didn’t know about that.
No issue board basically means that project is not maintained.

But anyway, there is nothing I can do.
Controls work in my latest code, and I can’t force Alula to merge it.

Those linked source ports are provided as-is, I have no control over them.

**Comment by rugk** [comment]
Uhm same issue here. So what exactly is newer now, I did not quite get it?

If this here is newer, could not you just add a website for [your version](https://github.com/k4zmu2a/SpaceCadetPinball), maybe simply publish that on GitHub Pages, that is very easy? Especially if the other version is really unmaintained?

Also @sbrl e.g. what are now the correct controls to control taht web game?

**Comment by k4zmu2a** [comment]
It is not that simple, let me explain.
My repo is the latest version of the game, all other repos are forked from it.

There is no way for me publish a web version because my code is for desktop only.
Emscripten source port is an independent project that I have no control over.

If you want something changed in Emscripten port, then petition its author.
If that project is abandoned, then someone needs to fork it.

**Comment by rugk** [comment]
> Emscripten source port is an independent project that I have no control over.

Well… if it is abandoned, then you could fork it back and integrate your changes…

**Comment by parkerlreed** [comment]
@rugk You are assuming they know or have any interest in Emscription. It's like asking someone who doesn't know Spanish to teach a class. There's no incentive to or knowledge of to make it the least bit useful.

**Comment by parkerlreed** [comment]
> e.g. what are now the correct controls to control taht web game?

The same as the default Pinball controls. Z and / and Space.

**Comment by k4zmu2a** [comment]
Well of course I could, but I’d rather not.
It does not make sense for me to fork a fork of my own project.
But mainly because I don’t like web development.

My strategy with this project is to target a single platform - generic desktop.
Leaving all the porting work to platform enthusiasts.

**Comment by rugk** [comment]
Ah I mistankenly thought it uses mainly the same code base as this one here with WebAssembly or whatever, but well… that's understandable of course then.

**Comment by k4zmu2a** [comment]
Readme is fine without detailed controls.

Source port authors should keep this in mind:  
Software development is rarely one and done process, continued support is essential.
