### ISSUE TITLE
Cross compiling with mingw complains about windres

### ISSUE THREAD

**Issue by krishean** [k4zmu2a/SpaceCadetPinball#54]
When I try to cross compile on Xubuntu 20.04 it fails with an error about not being able to find windres, I was able to fix it by adding the line:

`set(CMAKE_RC_COMPILER ${TOOLCHAIN_PREFIX}-windres)`

to the mingwcc.cmake toolchain file below the assembler line.

**Comment by k4zmu2a** [comment]
That’s a good find, added.
