### ISSUE TITLE
Text out of place and scrambled (?) when resized and UseBitmapFont set as 0

### ISSUE THREAD

**Issue by win98se** [k4zmu2a/SpaceCadetPinball#56]
When `UseBitmapFont` is set as `0` (by changing string table number 158), the text is out of place and scambled (?) when resized.

Screenshots:

![image](https://user-images.githubusercontent.com/11819816/137955544-50449a80-3aa8-4303-949b-35b25bffb872.png)

![image](https://user-images.githubusercontent.com/11819816/137955968-00cc2c07-7f27-43b8-b39f-e0568917128c.png)

**Comment by k4zmu2a** [comment]
I will try to add the alternative text scaling.
Under scaling I mean translation + bounding box and font scaling.

There is a related issue #28 that requests localization.
At the time I did not realize that it would depend on this feature.
I might actually do it and add original localized texts to v1.

**Comment by k4zmu2a** [comment]
System text scaling is in, check it out.
