### ISSUE TITLE
Windows XP with x86 binary

### ISSUE THREAD

**Issue by parkerlreed** [k4zmu2a/SpaceCadetPinball#7]
Trying to run the x86 on XP, it gives the typical "Not a valid Win32 application" error.  I double checked the exe and it's showing as PE32. 

Is the x86 supposed to run on XP or is it slightly too new to work?

**Comment by k4zmu2a** [comment]
No, x86 build from modern VS will not run on XP.
I forgot about this and didn’t add XP-specific build configuration.
To address this, I added XP build configuration and x86 build under v1.1.1 release.
X64 XP build is also possible, but I decided to omit it for now.

**Comment by parkerlreed** [comment]
Thanks! I figured that was the case. I'll try that out when I get home.

**Comment by parkerlreed** [comment]
Works great!

![PXL_20210907_213039282.jpg](https://user-images.githubusercontent.com/841440/132413548-6b0931dd-4969-48df-804e-4a9e0fd8c861.jpg)

**Comment by parkerlreed** [comment]
Before I go spawning a new issue, is the V2.0 x86WinXP supposed to be 32bit? Does not run on XP 32 bit for me (Not a valid Win32 application)

**Comment by parkerlreed** [comment]
Looks like it's plain 32bit but XP isn't liking it
```
[parker@t495 SpaceCadetPinballx86WinXP]$ file *
SDL2.dll:              PE32 executable (DLL) (console) Intel 80386 (stripped to external PDB), for MS Windows
SDL2_mixer.dll:        PE32 executable (DLL) (GUI) Intel 80386 (stripped to external PDB), for MS Windows
SpaceCadetPinball.exe: PE32 executable (GUI) Intel 80386, for MS Windows
```

**Comment by k4zmu2a** [comment]
Can confirm, packaging fault on my end.
Probably a regular build in that XP zip.
Updated XP release attachment with 2.01RC build, close enough.
