### ISSUE TITLE
Successfully built on Windows using MSYS2

### ISSUE THREAD

**Issue by krishean** [k4zmu2a/SpaceCadetPinball#70]
I was able to build on Windows 10/21H1 using the MSYS2 build environment/MinGW-w64 compiler and the SDL2/SDL2_mixer libraries available from libsdl.org:

```
# install prerequisites
pacman -S base-devel git mingw-w64-x86_64-gcc mingw-w64-x86_64-cmake mingw-w64-x86_64-SDL2 mingw-w64-x86_64-SDL2_mixer
wget https://www.libsdl.org/release/SDL2-devel-2.0.16-mingw.tar.gz
tar -xzvf SDL2-devel-2.0.16-mingw.tar.gz
wget https://www.libsdl.org/projects/SDL_mixer/release/SDL2_mixer-devel-2.0.4-mingw.tar.gz
tar -xzvf SDL2_mixer-devel-2.0.4-mingw.tar.gz
git clone https://github.com/k4zmu2a/SpaceCadetPinball.git
cd SpaceCadetPinball
mkdir build && cd $_
cmake .. -G "MSYS Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="-mwindows" \
    -DSDL2_LIBRARY=$(realpath ../../SDL2-2.0.16/x86_64-w64-mingw32/lib/libSDL2.dll.a) \
    -DSDL2_INCLUDE_DIR=$(realpath ../../SDL2-2.0.16/x86_64-w64-mingw32/include/SDL2) \
    -DSDL2_MIXER_LIBRARY=$(realpath ../../SDL2_mixer-2.0.4/x86_64-w64-mingw32/lib/libSDL2_mixer.dll.a) \
    -DSDL2_MIXER_INCLUDE_DIR=$(realpath ../../SDL2_mixer-2.0.4/x86_64-w64-mingw32/include/SDL2)
cmake --build .
```

The SDL2/SDL2_mixer libraries included in the MSYS2 packages are linked against libFLAC/libogg/libvorbis/etc, and will cause the exe to fail to link because of the line:

`set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -static")`

in CMakeLists.txt, so the workaround is to use the packages from libsdl.org which are not directly linked against extra libraries.

The resulting exe is fairly large at 12.9MB for some reason, and comes out much smaller (around 1.8MB) if you comment out the line about static linking, but then you have to copy the files:

```
/mingw64/bin/libwinpthread-1.dll
/mingw64/bin/libstdc++-6.dll
/mingw64/bin/libgcc_s_seh-1.dll
```

to the game data directory as well as the SDL2/SDL2_mixer libraries and compiled exe.

Hopefully this is useful as an alternative to compiling with Visual Studio.

**Comment by k4zmu2a** [comment]
Success story was heard.
