### ISSUE TITLE
[V2 only bug(?)] High Score dialog not shown when Show Menu is disabled

### ISSUE THREAD

**Issue by win98se** [k4zmu2a/SpaceCadetPinball#76]
As in title, also the dialog is only immediately shown once (if you achieved two or more high scores during it) when top left Menu button is clicked.

**Comment by k4zmu2a** [comment]
Can confirm, bug in v2 ImGui code.
Should be fixed now.

**Comment by win98se** [comment]
Fixed in https://github.com/k4zmu2a/SpaceCadetPinball/issues/82#issuecomment-962475993. Thank you!
