### ISSUE TITLE
Thanks! -- not an issue, just a thanks!

### ISSUE THREAD

**Issue by kencu** [k4zmu2a/SpaceCadetPinball#78]
This built right through on MacOS Monterey using the sdl2 libraries from homebrew in a minute or two, and with the resources from my old Windows Pinball installation, works just great!

Well done -- I had no idea you could decompile an older game like this and remake it in SDL2. 

now I'm in for some serious wasted time!

**Comment by rikimbo** [comment]
+1 to this. I just tried this out on an Ubuntu 20.04 box and it's super cool to play this natively there.

**Comment by k4zmu2a** [comment]
You are all welcome.
I believe that this iconic game deserves brighter future than old XP builds and Wine.

Everything is possible if you apply yourself - this project started as a training exercise that went too good not to publish.
The hardest part was making a decompilation you can work with, not SDL port.

**Comment by dobragab** [comment]
+1. I've made clones for multiple iconic games, some in SDL (Snake from Nokia 3310, Minesweeper from Windows XP), some in other frameworks (Solitaire XP in Java, Freecell on Android). 

Once I wanted to make a Pinball clone as well, but I realized all the objects and physics would be hard to reverse engineer, so I started decompiling Pinball and cleaning up the source to recompile. I gave up pretty early due to lack of experience in this area, lack of WINAPI knowledge, etc.

Knowing what I gave up and seeing that you actually did that makes me really appreciate your work.

**Comment by sgumiel** [comment]
I am a newbie with macOs and all these environment (make, cmake, etc). Could you explain me what commands do i have to execute to create the binary file to play?
I've just installed homebrew, and executed
brew install SDL2
brew install SDL2_mixer
And with the cmake gui i've executed CMAKE (I suggest)
What more do i have to do?

thanks

**Comment by kencu** [comment]
Something like this recipe works in a minute or two:
```
cd ~
mkdir src
cd src
brew install SDL2 SDL2_mixer cmake
git clone https://github.com/k4zmu2a/SpaceCadetPinball
cd SpaceCadetPinball
mkdir build
cd build
cmake ../
make
cd ../bin
```
and there is your executable:
```
-rwxr-xr-x   1 me  staff  2370880 18 Nov 00:27 SpaceCadetPinball
```
just copy that into your Pinball folder you got from WindowsXP or similar

**Comment by sgumiel** [comment]
Thanks in advance. 
It works fine!! but when i execute ./SpaceCadetPinball i've got this error
"Could not load game data" The .dat file is missing

aka an image
![Captura de pantalla 2021-11-18 a las 11 12 02](https://user-images.githubusercontent.com/17992881/142396282-ebeb1cec-2a09-4806-a28e-996eaf0f90c8.png)

**Comment by 0x5066** [comment]
I wonder why the .dat file is missing, certainly the readme would surely mention that...

**Comment by k4zmu2a** [comment]
It was fun while it lasted, “the .dat file is missing” haunts us all in some way)
I slightly improved that message btw.
