### ISSUE TITLE
Map Exit Button on Controller

### ISSUE THREAD

**Issue by rikimbo** [k4zmu2a/SpaceCadetPinball#79]
I played this with a controller, and the default configuration works great (the shoulder buttons for the paddles and "start" to pause are very intuitive). However, as far as I can tell, there's no way to exit the game with the controller only. Would it be possible to map a key on the controller to exit? Perhaps the "select" button by default?

**Comment by k4zmu2a** [comment]
Added exit on controller select when paused.
Just select felt too easy to hit accidentally.

**Comment by rikimbo** [comment]
This works great, thanks!
