### ISSUE TITLE
The .dat file is missing - Linux/X11

### ISSUE THREAD

**Issue by acedogblast** [k4zmu2a/SpaceCadetPinball#8]
Hello I complied the game from the master branch but when I run the executable it gives me an error message with "The .dat file is missing." I assume I am missing a file somewhere?

**Comment by acedogblast** [comment]
Never mind. I see the final executable needs to be copied into the original game files.

**Comment by acosonic** [comment]
I got the same error, where to copy it?

**Comment by acosonic** [comment]
I have copied all files from wine's install dir and it works :)
