### ISSUE TITLE
Load .DAT from another directory

### ISSUE THREAD

**Issue by NicolaSmaniotto** [k4zmu2a/SpaceCadetPinball#80]
Not a bug, more of a feature request. Would it be possible to load the assets from a directory that isn't the one where the binary is installed?
The question comes from the fact that on Linux, the compiled executable is probably located in `/usr/bin`, while I think the ["standard" directory](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) for the DAT and the sound files would be `$XDG_DATA_HOME/SpaceCadetPinball`.
This separation would allow each user to have their (preferred) data files in their own folders, without the need to provide them for the whole system.

**Comment by k4zmu2a** [comment]
Yes, that is possible.
I will add SDL_GetPrefPath as a fallback after binary folder.
On Linux it should be ~/.local/share/SpaceCadetPinball, close enough.

**Comment by NicolaSmaniotto** [comment]
`$HOME/.local/share` is the value to be used if `$XDG_DATA_HOME` is unset. If support for this is to be added, I think it would be better to also respect this environment variable.

**Comment by k4zmu2a** [comment]
Your request is complete.
I tested with $XDG_DATA_HOME, it is used by SDL_GetPrefPath when set.

**Comment by NicolaSmaniotto** [comment]
Thank you for all your great work!
