### ISSUE TITLE
Wrong point rewards for accepting missions

### ISSUE THREAD

**Issue by LoneFox78** [k4zmu2a/SpaceCadetPinball#81]
Accepting Target Practice mission gives 20000 points, while it should give 10000. Similarly, Bug Hunt gives 30000 instead of 20000, and Rescue Mission gives 0 instead of 20000. I suspect there are others, but I'm not good enough at this game to get any further than these...

**Comment by k4zmu2a** [comment]
This is a bug introduced by decompilation.
Fixed in v1 and v2.

**Comment by k4zmu2a** [comment]
Bugfix released in v2.0.1
