### ISSUE TITLE
Cannot play Full-Tilt version after 2.0 version

### ISSUE THREAD

**Issue by HarGabt** [k4zmu2a/SpaceCadetPinball#82]
The 2.0 release works only with XP version of Space Cadet. Attemting to run Full-Tilt version gives error "The .dat file is missing" even though older versions before 2.0 worked.

**Comment by k4zmu2a** [comment]
V2 is supposed to work with FT, nothing has changed in this area since v1.
Something is probably wrong with your folder structure, it should be:
•	GameFolder
o	SpaceCadetPinball.exe
o	CADET.DAT
o	SOUND

Things to try:
Try running both v2 and v1 from the same game folder.
Check FT version, I test with 1.1.

**Comment by HarGabt** [comment]
My folder structure looks like this:
![изображение](https://user-images.githubusercontent.com/44652400/140468014-df789083-6411-42ea-b673-c12a3da41910.png)

>Check FT version

You mean checking the version of original release?

**Comment by k4zmu2a** [comment]
Your folder structure looks ok.
This same game folder used to work with v1.x?
It looks like this folder is from 16-bit version of FT, judging by wavemix.dll.
Just in case, try with 32-bit version.

Yes, check the version of original FT, in Help -> About FT.
It could be either 1.0 or 1.1, and I never tested 1.0 release.
If it is indeed FT 1.0, upload it here, I might be able to add support for it.

**Comment by HarGabt** [comment]
Can't run the original executable, but it looks like i have initial version of Full Tilt.
![изображение](https://user-images.githubusercontent.com/44652400/140477471-a1807a4e-3a0c-4e72-a109-d65bf6fb4bc0.png)

I can upload its executable here, if you need
[CADET.zip](https://github.com/k4zmu2a/SpaceCadetPinball/files/7481555/CADET.zip)

**Comment by k4zmu2a** [comment]
It is 16-bit, possibly 1.0. I don’t a VM to run it at the moment.
Does this 16-bit data run with any of my v1.x releases?

What I need is CADET.DAT file, not exe. Or just upload the whole folder.
If you have 32-bit build of FT 1.0, upload it as well.

**Comment by HarGabt** [comment]
>Does this 16-bit data run with any of my v1.x releases?

Yes, it does.

here are .dat files from 1.0 and 1.1 (apparently 32-bit, as it runs even on Windows 11)
[CADET.dat from 1.1.zip](https://github.com/k4zmu2a/SpaceCadetPinball/files/7481746/CADET.dat.from.1.1.zip)
[CADET.dat from 1.0.zip](https://github.com/k4zmu2a/SpaceCadetPinball/files/7481739/CADET.dat.from.1.0.zip)

**Comment by k4zmu2a** [comment]
Those two CADET.DAT have the same hash, also the same as my FT 1.1 .dat file.
I don’t see any reason why v2.0 would not run with any of them.

I assume “CADET.dat from 1.0.zip” is .dat file from 16-bit FT 1.0.
Then what is “CADET.dat from 1.1.zip”?

**Comment by HarGabt** [comment]
"1.1" is meant to be from 1.1 version

Okay, some time later i redownloaded full-tilt redistributive, and all of a sudden every original assets (1.0 and 1.1) works. I don't know...

Maybe we should close this issue for good, because i don't know how and why it did and did not work.

**Comment by HarGabt** [comment]
I reopen this issue because i found the reason why 2.0 version doesn't work

It all had to do with path names containing non-latin characters. The name of the folder with game assets had cyrillic characters, thus giving that error with certain file missing. I renamed the folder with only latin characters and now it works!

**Comment by k4zmu2a** [comment]
Thank you for finding the root cause - a classic Windows error with Unicode paths.
The fix is ready, try it out in the attached build.
[SpaceCadetPinball_v2.0.1RC.zip](https://github.com/k4zmu2a/SpaceCadetPinball/files/7490855/SpaceCadetPinball_v2.0.1RC.zip)

**Comment by HarGabt** [comment]
I confirm - this build works, no issue with name paths

**Comment by k4zmu2a** [comment]
Issue resolved.
