### ISSUE TITLE
`SDL Error: Couldn't open /usr/local/lib/timidity/...` on Mac

### ISSUE THREAD

**Issue by eggplants** [k4zmu2a/SpaceCadetPinball#86]
## What

On Mac, `brew install timidity` installs .pat files into not `/usr/local/lib/timidity` but `/usr/local/share/freepats`.
I want to know is there any way to specify a directory of pat files when building.

Note: *By the way, the game starts up fine, and I can play it with no sound, control, or graphic problems.*

## Environment

```shellsession
$ uname -vorm
21.1.0 Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:23 PDT 2021; root:xnu-8019.41.5~1/RELEASE_X86_64 x86_64 Darwin
```

## Details

I had built with below commands on Mac:

```bash
brew install sdl2 sdl2_mixer cmake timidity
git clone --depth 1 https://github.com/k4zmu2a/SpaceCadetPinball
cd SpaceCadetPinball
cmake . && cmake --build .
git clone --depth 1 https://github.com/FmasterofU/WinXP-Pinball
mv WinXP-Pinball/Pinball/* bin
rm -rf WinXP-Pinball
```

When I have launched the game,  it cause errors:

```shellsession
$ ./bin/SpaceCadetPinball
Using SDL renderer: metal
SDL Error: Couldn't open /usr/local/lib/timidity/Drum_000/055_Cymbal_Splash.pat
$ ln -s /usr/local/share/freepats /usr/local/lib/timidity
$ ./bin/SpaceCadetPinball
Using SDL renderer: metal
SDL Error: Couldn't open Drum_000/055_Cymbal_Splash.pat
SDL Error: Unknown touch device id -1, cannot reset
$ ls  /usr/local/lib/timidity/Drum_000/055*
/usr/local/lib/timidity/Drum_000/055_Cymbal_Splash.pat
```

**Comment by k4zmu2a** [comment]
I don’t see such option in SDL API, path to pats is probably set in the timidity config file.
Since midi works in the end, SDL probably has some fallback mechanism.

**Comment by eggplants** [comment]
I think this game is not required midi files. So it is good to prevent MIDI from being loaded.

**Comment by k4zmu2a** [comment]
What do you mean, midi is not required?
3DPB music is in MIDI format, FT has music in MIDS or MIDI.

**Comment by eggplants** [comment]
MS Pinball doesn't seem to use midis under `/usr/local/lib/timidity/`.

**Comment by 0x5066** [comment]
mid and midi are practically the same

**Comment by k4zmu2a** [comment]
I don’t get it.
Under midi I understand .mid or .mds music files from the game data.
SDL uses timidity to render said music using sound banks (that are not bundled with the game), it does not inject its own midis into the game.
So naturally, the game does not use midi from /usr/local/lib/timidity/ or somewhere else.
