### ISSUE TITLE
Use more authentic fonts

### ISSUE THREAD

**Issue by dobragab** [k4zmu2a/SpaceCadetPinball#87]
Once I tried Hungarian translation (which is my native language, I grew up playing this) I immediately noticed that Arial doesn't match the original vibe:

![original](https://i.imgur.com/l8XUmOG.png)

I went ahead and I can see three real options to get better results, focusing on European languages with Latin characters:
1. Decompile a Hungarian (or any localized) exe to get original font rendering mechanism. I tried using Process Monitor, and it looks like it isn't using a Windows font, but some built-in rendering mechanism. Note that I only tried Hungarian 3DSC version.
2. Find the original font in TTF, and use that instead of Arial.
3. Use an approximation font.

Good news is, 2. does exist, it's called PIXymbols WINmenu W01 Menu, I tried that, and it actually is the original font, with 17 px base size. I don't know about higher resolutions, I don't have FT.

![winmenu](https://i.imgur.com/Sr0Ulz4.png)
[see in a bigger window](https://i.imgur.com/O2mF4eg.png)

Bad news are:
* It doesn't contain some accented characters from half the supported languages. I spent a few hours with a font editor, and now I have added all accented characters for all the languages that Pinball has localizations for. Most of them were just putting existing accents on basic latin characters, only Polish `Ł` was tricky.
* The original game just replaced the characters with accent-less ones in the texts. I'm pretty sure we don't want to follow that path. 
* I don't know whether we can redistribute it. Either the third-party one, or with my modifications. It's possibly the greyest of grey areas, as the font was visually copied from the game itself (or from some other Microsoft or EA property, who knows).
* I tried rendering the texts with WinMenu font plus falling back to 3. when there is a missing character, MS Sans Serif would have been a good candidate, but that didn't work and can't really work for multiple reasons. It ended up being a lot easier to fix the font itself.

So, assuming 2. can be a no-go, I explored 3. and found three similarly looking, authentic XP fonts: MS Sans Serif (a.k.a Helv), Helvetica and Tahoma (also available as MS Shell Dlg 2). All of which are most likely installed on all the target systems of WindowsClassic branch: Windows versions and Wine.

I used 16 px Bold fonts, with `NONANTIALIASED_QUALITY`.

This is how they look:

**MS Sans Serif**
![MS Sans Serif](https://i.imgur.com/0lNwaOL.png)
[see in a bigger window](https://i.imgur.com/Zhw3Fl2.png)

**Helvetica**
![Helvetica](https://i.imgur.com/vPrf8I3.png)
[see in a bigger window](https://i.imgur.com/jmxvSX9.png)

**Tahoma**
![Tahoma](https://i.imgur.com/OLZNeIx.png)
[see in a bigger window](https://i.imgur.com/1ihZDsC.png)

I prefer MS Sans Serif out of these, but I think accented characters look more authentic with Tahoma.

As I have no means to properly perform option 1., I'd recommend trying to open WinMenu font, if that's not found then fall back to MS Sans Serif. And provide installation link for the WinMenu font.

There's a huge difference between 2, and 3. though: WinMenu font is a bitmap font, so it basically doesn't scale. Others are TrueType fonts, and scale nicely and (in this context) weirdly. We could get bitmap font-like results with rendering the fonts with fixed size, and then stretching that out on the final screen.

**Comment by k4zmu2a** [comment]
I don’t think the original used default SYSTEM font for its artistic value.
I decompiled a couple of localized versions, to see if they setup the font in some way.
And no, they just DrawText without any font setup.
It is possible to follow the original and use SYSTEM font, the problem is that it is a bitmap font and does not scale.

Arial is just the first font I tried that had proper TTF scaling.
I am fine with changing non hieroglyphic font to something else (like MS Sans Serif), as per option 3).
I wouldn’t go with option 2), standard fonts are enough for this application.
I want to keep Clear Type enabled, since we are rendering text directly to screen.

**Comment by k4zmu2a** [comment]
I have tested your font selection against Arial:
•	MS Sans Serif looks pixelated and has tight kerning.
•	Helvetica looks the same to me.
•	Tahoma has tight kerning.
None of them look that much better to me.

Kerning is important because most stings have manual line breaks in them.
I don’t imply that Arial line width is 100% accurate, but it is close in cases that I tested.

As a compromise, I can offer you a change of only Hungarian font to your selection, except for MS Sans Serif and its likes.
![3DBP font challange1](https://user-images.githubusercontent.com/33288308/140715191-779aa816-0e5d-44c1-a143-1cf88d58b26e.png)

**Comment by dobragab** [comment]
It took me two nights to find what was the font that appears on my "MS Sans Serif" screenshot. That font clearly wasn't pixelated to me when I took the screenshot, and I carefully double-checked every screenshot to make sure I don't confuse them.

Today I realized that MS Sans Serif scales in an incredibly weird way. It acts as a Bitmap font in some sizes, and as a TrueType font in some others. What you can see in my screenshot is actually MS Sans Serif Bold at size 16.

I have no idea what's going on, and how is MS Sans Serif falling back to that font, what font is the one it's falling back to (can't see MS Sans Serif in FontLink registry at all), and how to access directly that font. To me, that font is clearly superior to all other choices if you want to stick to non-pixelated fonts. 

Also, please test in a language that uses latin-based characters. I'd currently suggest using these "more authentic" fonts only for those languages. And add a menu option to use "original" fonts, i.e. System or WinMenu (if installed). I'm happy to actually develop these.

**Comment by k4zmu2a** [comment]
What looks superior to you, does not necessarily look superior to me.
My plan is to use a single font that is shipped with Windows for all non-hieroglyphic languages.
I don’t want any font configuration menus or options.

**Comment by dobragab** [comment]
My goal is the same as yours, use a non-pixelated font that is as close to the original, and is shipped with Windows. I'm fine if the option is just a hidden menu entry, like TargetFrameRate.

I'll try to find out if that "MS Sans Serif" variant is accessible through WinAPI.

**Comment by dobragab** [comment]
Turns out it's `sserife.ttf` and its localized versions, `sserife?.ttf` files. And I didn't have any success in opening only those with WinAPI, because they share the same font family name and other metadata (that LOGFONT contains) as `sseriff.ttf` and `sseriff?.ttf` which look different, and pixelated in some sizes.

Do you have an idea if we can access `sserife.ttf` through GDI in any way?

**Comment by k4zmu2a** [comment]
I think you are overcomplicating things with MS Sans Serif.
I believe it is always pixelated with pixilation amount related to font weight.
Here it is with various combinations of AA and font weight:
![3DBP font challange2](https://user-images.githubusercontent.com/33288308/141675727-67401525-bc07-4356-8342-57345cbc4a0f.png)

While playing with this font, I found a pretty big flaw - accented characters handle AA and scaling differently from base font.
They also have different pixilation pattern, clearly borrowed from some other font.
This produces quite jarring results:
![3DBP font challange3](https://user-images.githubusercontent.com/33288308/141675744-c396c0fb-9c62-4362-b72e-efb36e378435.png)

**Comment by dobragab** [comment]
I could make MS Sans Serif work, see this commit: https://github.com/dobragab/SpaceCadetPinball/commit/cf424cef8d7cf32710b25675ff72b6e33f326f81

It is pretty complicated, as multiple versions of the font are installed by default, namely `sserife.fon` and `sseriff.fon`, and WinAPI doesn't provide an API to select, as basically almost all of their attributes are the same. Luckily, its codepage variants aren't installed (at least for me) by default, so I can choose e.g. `sserifee.fon` for Eastern European languges by AddFontResourceEx and specifying EASTEUROPE_CHARSET in LOGFONT, and this also solves accented characters.

Then the next problem to solve is scaling, it doesn't scale well. So instead of specifying scaled fontSize, I choose an exact size, render it to a new bitmap, and then blit the bitmap scaled to the window.

As it's this complicated, I'm not sure we want to go forward with this. Please play with my commit and check the results.

**Comment by k4zmu2a** [comment]
Tried your font code.
It works and the scaling looks correct, did not test on XP.

Things I didn’t like:
•	StretchDIBits scaling ruins font quality, for example letters K, s. StretchDIBits has no business rendering fonts.
•	Too much complexity for what is achieved. I am looking for higher quality results with less complexity, not the other way around.
If this your end game with MS Sans Serif, just forget about merging it)


![3DBP font challange4](https://user-images.githubusercontent.com/33288308/141807269-f46ce9fe-b4ee-41c9-a55e-41e0604f8a19.png)

At first, I thought that adding font family option will be fine.
But now I see that such option will also need other CreateFont parameters, like weight, AA, height and more.
The conclusion: adding such option is not worth it.

**Comment by dobragab** [comment]
Yeah I don't like this solution either.

Can I add a hidden registry entry to use "System" or "WinMenu" fonts?

**Comment by win98se** [comment]
I need to point out a thing about MS Sans Serif - there are two fonts within the same family. “**MS Sans Serif**” is always pixelized (this font is also not TrueType, named `sserife.fon`; Fonts in .FON file extension are mostly used in Windows 3.x UI display, AFAIK), and “**Microsoft Sans Serif**” is the more modern variant of the same font in TrueType (named `micross.ttf`; It's even in OpenType as of Windows 10!).

Not sure if it's helpful, but since this project is only for Windows XP and above, there is no point to use the former font anymore - maybe try to use the latter one for better results, I think.

**Comment by k4zmu2a** [comment]
Sorry, I don’t want such option added.
Default system font does not scale at all, does not work with resizable window.
I don’t want to load any nonstandard fonts either.

This Microsoft Sans Serif font is much better in scaling and AA department.
And it works in Windows XP.

Differences with Arial are marginal, with slightly tighter kerning.
![3DBP font challange5](https://user-images.githubusercontent.com/33288308/141933143-7eb6030c-772b-4cf2-ae2b-8ec4e945d1bf.png)

**Comment by dobragab** [comment]
I managed to make "System" font work similarly to what I did with MS Sans Serif, but without the complicated manual stretching. Practically GDI+ will stretch the bitmap font only by integer factors.

This way, 640x480 version looks exactly like the original (pic 1). (TBH even better, as I could make accented characters work.) 800x600 and 1024x768 (pic 2) are reasonable but not pretty, and this starts to make sense when the window is maximized to high resolutions like FullHD (pic 3) or 2K.

[640x480](https://user-images.githubusercontent.com/10715919/147977752-4a474af7-e6fa-4976-a857-aeda5025088b.png)
[1024x768](https://user-images.githubusercontent.com/10715919/147977757-5768531b-f371-4bb6-8742-ed6582b1d27f.png)
[FullHD](https://user-images.githubusercontent.com/10715919/147977743-bdcaf894-5f36-461a-91bf-3d8cad3473aa.png)

_Note that this is a registry option only, so it is intended for "power" users (like me) who want Pinball to look as authentic as possible, i.e. pixelated._

My changes still look for WinMenu and use if it's available, as it scales way better than System. I can remove that part if necessary.

**Comment by k4zmu2a** [comment]
Latest version looks way better.
The complexity is reasonable and it does not sacrifice the AA.
System .fon seems to scale in non-continuous steps.
Might be small in some window sizes but better than not scaling at all with default system font.

I am fine with adding this, if it works on XP.
Open a PR, I will suggest some changes there.

**Comment by dobragab** [comment]
Solved by #119.
