### ISSUE TITLE
[V2 only bug] Borders not properly filled with black when maximized

### ISSUE THREAD

**Issue by win98se** [k4zmu2a/SpaceCadetPinball#88]
On Ubuntu 20.04.

![2021-11-08 23-18-32 的屏幕截图](https://user-images.githubusercontent.com/11819816/140768835-5561eec8-ef00-4b84-a89c-21248b518877.png)

Notice the left part, there are some remnants in the supposed black border area after maximizing and clicking on menus.

**Comment by win98se** [comment]
Also hijacking this issue with another one - for V1 on Wine, the language is forced to be system language (Simplified Chinese in my case) - changing them to any other language just doesn't work.

![image](https://user-images.githubusercontent.com/11819816/140772089-5176442e-c60e-43a7-9db8-b112bb80a2ca.png)

Music also doesn't work, but it should be expected to, I guess.

If you think this can be considered as an issue (as running V1 on Wine isn't supported scenario, right?), and if necessary, I can create another one for it.

**Comment by parkerlreed** [comment]
V1 on WINE is a mixed bag. You need a MIDI daemon running and configured for music. Sounds are always going to be a miss with how WINE handles the old odd sample rate. Pretty much not worth trying to maintain V1 in WINE since the native port exists now.

The border issue may be due to SDL turning off your compositor on launch. Trying launching with it already off (if possible) to see if that issue persists. Maximizes and fullscreens fine on Plasma for what it's worth.

**Comment by win98se** [comment]
> Pretty much not worth trying to maintain V1 in WINE since the native port exists now.

Good point, this is also why I didn't create a separate issue for it.

> The border issue may be due to SDL turning off your compositor on launch. Trying launching with it already off (if possible) to see if that issue persists.

I'm using Ubuntu 20.04 with GNOME as DE. How do I manually turn off the compositor?

**Comment by parkerlreed** [comment]
Looks like Gnome doesn't have a manual option. https://www.reddit.com/r/leagueoflinux/comments/e0c6n5/how_can_i_disable_compositor_on_gnome_to_improve/

That's about my extent of knowledge on that front. Hope you can get that solved.

**Comment by win98se** [comment]
> Looks like Gnome doesn't have a manual option. [reddit.com/r/leagueoflinux/comments/e0c6n5/how_can_i_disable_compositor_on_gnome_to_improve](https://www.reddit.com/r/leagueoflinux/comments/e0c6n5/how_can_i_disable_compositor_on_gnome_to_improve/)

In fact I read the same Reddit post too. ;)

> That's about my extent of knowledge on that front. Hope you can get that solved.

Thank you.

**Comment by k4zmu2a** [comment]
On leftovers in void: I use clear on every frame, if that doesn't work I don't know what will.
I suppose rendering full screen quad will wipe the screen, but that is just wasting bandwidth. 
On wine:  
 Sound should be as good (or bad) as the original.
 Language switch: I have code paths for XP and Vista+, I don't know what wine needs, might be just broken.

**Comment by win98se** [comment]
![image](https://user-images.githubusercontent.com/11819816/140898398-6da372c6-dbc7-4c79-ad35-64b518d628db.png)

So for further testing, I've installed vanilla Debian 11 on Hyper-V with LXQt as DE, and that bug doesn't appear.

**Comment by k4zmu2a** [comment]
We can summarize that this void issue is exclusive to Ubuntu DE.
Possible cause – conflict of SDL and compositor.

I doubt that buffer clear is not working, hard to imagine OpenGL failing like that.
This means that the image shown in the window is somehow processed after SDL GL calls.
It looks like the final image is selectively assembled from game output, we can see two updated regions on top of the old buffer: game table and collapsed menu button.

I am not adding any hacks just yet, I need more information.
Maybe once I get WSLg on Win10 I will test it myself.

**Comment by li20034** [comment]
Actually, it gets worse. If you enable integer scaling, and drag one of the ImGui windows near the borders, this happens.
![image](https://user-images.githubusercontent.com/23200179/147395596-94985c0e-4db6-465b-bb90-32ecd9936018.png)
I'm using Linux Mint Xfce 20.2 (based on Ubuntu 20.04), and this occurs regardless if I enable or disable the compositor in Xfwm. And indeed if you replace SDL_RenderClear in winmain.cpp with SDL_DrawFillRect (which is the hack that was discussed here), everything works. Also, without any hacks, setting LIBGL_ALWAYS_SOFTWARE=1 does not help, but setting SDL_RENDER_DRIVER=software does.

**Comment by k4zmu2a** [comment]
Alright, it is time to address this issue.
Added hack - second clear via full screen quad.

Running two clears might lower the performance.
I did not notice any impact in my tests with dx9 and opengl.

Source ports are advised to stick to one clear operation, probably original SDL_RenderClear.

**Comment by k4zmu2a** [comment]
The fix was released as part of 2.0.1

**Comment by win98se** [comment]
Finally got the chance to test whether this bug is fixed on Ubuntu (because I was too busy) - it's now fixed. Thank you!
