### ISSUE TITLE
[V1 only] Suggestion: No longer set screen resolution when selecting Full Screen

### ISSUE THREAD

**Issue by win98se** [k4zmu2a/SpaceCadetPinball#90]
Since we already can maximize the game window, why not make it just maximize the screen, just like V2's behaviour? ;)

**Comment by k4zmu2a** [comment]
Because exclusive full screen produces noticeably higher quality upscale than GDI.
GDI quality cannot be “cranked up” any higher.

**Comment by win98se** [comment]
That's a good point, however it does trouble me (just personally) a bit and in some ways if I'm not using native resolution for my monitor.

Closing this one for now, I guess.

**Comment by k4zmu2a** [comment]
I think this checks out: play an old game – get the old treatment)
I know that changing resolution is uncool nowadays, I would have removed it if I was confident in GDI.
