### ISSUE TITLE
Ability to start new game with controller

### ISSUE THREAD

**Issue by rikimbo** [k4zmu2a/SpaceCadetPinball#92]
With #79 resolved (thanks!), the game is mostly playable with just a controller. When you run out of balls, though, I don't think you can do these actions with the controller only:
1. Dismiss the High Score screen.
2. Start a new game (F2 on keyboard).

Could those actions be mapped to controller buttons so that play can continue? My 3-year-old would love it. :)

**Comment by k4zmu2a** [comment]
Yes, that is all possible.
GUI that I am using has keyboard/controller navigation feature, so I just enabled that.
It seems to work, might be rough in some places.
To focus away from the game to main menu, you need to press ctrl-tab or hold x (or whatever equiv.) on controller.

**Comment by k4zmu2a** [comment]
Menu navigation was released in v2.0.1
