### ISSUE TITLE
cmake missing install step?

### ISSUE THREAD

**Issue by colemickens** [k4zmu2a/SpaceCadetPinball#95]
Hi, I'm trying to package this for Nix / NixOS / nixpkgs, but am hitting an issue after build succeeds:

```
       > [ 94%] Building CXX object CMakeFiles/SpaceCadetPinball.dir/SpaceCadetPinball/TTripwire.cpp.o
       > [ 95%] Building CXX object CMakeFiles/SpaceCadetPinball.dir/SpaceCadetPinball/TWall.cpp.o
       > [ 97%] Building CXX object CMakeFiles/SpaceCadetPinball.dir/SpaceCadetPinball/winmain.cpp.o
       > [ 98%] Building CXX object CMakeFiles/SpaceCadetPinball.dir/SpaceCadetPinball/zdrv.cpp.o
       > [100%] Linking CXX executable ../bin/SpaceCadetPinball
       > [100%] Built target SpaceCadetPinball
       > installing
       > install flags: SHELL=/nix/store/svxmj4xahyjqq4lciisvgi1fwl5bxpdd-bash-5.1-p8/bin/bash install
       > make: *** No rule to make target 'install'.  Stop.
```

I'm guessing I can skip the install phase and manually copy the binary executable, but presumably all users would benefit from the cmake file doing this properly. (I have almost zero experience with cmake or I'd try to do it).

**Comment by k4zmu2a** [comment]
I decided not to mess with the topic of installation on Linux.

In CMake, a simple default install will look like this:
install(TARGETS SpaceCadetPinball)

**Comment by k4zmu2a** [comment]
Install target was added as part of 2.0.1 release.
