### ISSUE TITLE
Resolution/scaling could be handled a bit better

### ISSUE THREAD

**Issue by vaguerant** [k4zmu2a/SpaceCadetPinball#97]
Hi, amazing project! I've been playing around with it for a couple of days now both on the PC version and IntriguingTiles's Wii U port, and I've noticed that the scaling can be tough to get a real handle on.

Just for reference, here's a screenshot of the original game, displaying in a 640\*480 window:
![Screenshot](https://www.mobygames.com/images/shots/l/198987-microsoft-windows-2000-included-games-windows-screenshot-table.png)

As you can see, the table doesn't fill the whole window/screen vertically. Just opening it up in an image editor, the table height is 416 pixels. This decompiled version, however, seems to just fill whatever window size you give it, making it very difficult to get sharp pixels. If you want sharper pixels and toggle the Graphics > Linear filtering option off, it's almost impossible to get a native resolution (or 2x native, etc.) image because you just have to eyeball it, or else use a third-party window resizing tool to match what you want. This heavily impacts the usability of the nearest-neighbor filter.

My suggestion would be one or both of a couple of things:
1) include options in the menu to resize the window to 1x,  2x, 3x, etc. multiples of the original image size (plus window borders, etc.)
2) include an option (next to Uniform Scaling seems sensible) for Integer Scaling, where the game will scale to the greatest integer value it can within the window provided (e.g. in a 640*480 window, display over 416 lines, in a 1920\*1080 window, display over 832 lines, etc.

This is particularly relevant downstream, where the Wii U comes with a controller with its own 854\*480 screen. Ideally, Space Cadet Pinball should be able to run with sharp 1:1 pixels rather than stretching from 416 to 480, but the project as it exists currently doesn't really accommodate this goal.

**EDIT:** Based on eyeballing it and manually resizing, it looks like the internal resolution the game renders to is 600\*416, is that correct? I'm able to get clean multiples by using those values and then adding the size of the window decorations when setting a window size, e.g. 1200\*832 is a 2x scale of that presumed internal resolution, and adding on 53 pixels (vertical) and 2 pixels (horizontal) for window decorations/menus, I can get what looks like a perfect 2x image by resizing my window to exactly 1202\*883:
![2x native screenshot](https://user-images.githubusercontent.com/5259025/142752524-2fd63e2c-8666-428a-bb75-fe6f4e50621d.png)

**EDIT2:** If I'm reading this right:
https://github.com/k4zmu2a/SpaceCadetPinball/blob/3b7dc0dae2b798e84ff02bfe0c2a6eb75fc29fad/SpaceCadetPinball/winmain.cpp#L103-L110
I think if I wanted to change the default window size to a 2x scale, I would want `1200, 851,` there. That's 832 lines of game plus 19 lines of menu. This is the same value used to set up the resolution on Wii U currently (1280\*720), but again that is currently a limitation of SDL on Wii U, all SDL software is forced to use that to work correctly.

**EDIT3:** Learning things all over the place, I didn't realize that Full Tilt Pinball has higher-res assets than the free Windows XP version, running at up to 960\*666 internally. All of the above was written on the assumption that all versions of the game run at 600\*416, which was obviously incorrect, but I think the idea remains the same, it would be nice to have integer scaling options--just that I now realize they need to accommodate multiple resolutions.

**Comment by k4zmu2a** [comment]
Hello, you sure wrote a lot of text)

You request is understandable, I don’t see why not.
Added variant 2 - Integer Scaling option.

As you discovered from the code, there are three pairs of window/table resolutions.
600*416 is the lowest table size, the only one supported by 3DPB data.
Window size is mostly irrelevant in v2 - main menu is part of the client area.
Table resolution == client area in the original.
ImGui menu height is not constant, you should not rely on it staying 19px.

**Comment by vaguerant** [comment]
Awesome, thank you! Very much appreciate this feature. Sorry for writing so much.

Thanks also for the tip re: ImGui menu height, that's good to know.

**Comment by k4zmu2a** [comment]
You are welcome.
Request fulfilled.
